apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi-python
  namespace: sparkapplication
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: spark:3.5.0
  imagePullPolicy: IfNotPresent
  mainApplicationFile: https://raw.githubusercontent.com/vipmarwah/pythonprogs/main/prog.py
  sparkVersion: 3.5.0
  sparkConf:
    "spark.kubernetes.namespace": "sparkapplication"
  driver:
    labels:
      version: 3.5.0
    cores: 1
    coreLimit: 1200m
    memory: 512m
    serviceAccount: spark-spark-operator-spark
  executor:
    labels:
      version: 3.5.0
    instances: 1
    cores: 1
    coreLimit: 1200m
    memory: 512m